import { readFileSync, writeFileSync } from "node:fs";

const filePath = "/home/ubuntu/workspace/app/src/frontend/src/components/PaintingApp.tsx";
const lines = readFileSync(filePath, "utf8").split("\n");

// Lines are 1-indexed in the editor; array is 0-indexed
// Replace lines 13219–13572 (inclusive) with the RightSidebarArea import and usage
// The replacement block:
const replacement = [
  `          {/* Right panel: Navigator + Layers */}`,
  `          {/* On mobile: hidden when collapsed (button in canvas overlay handles toggle) */}`,
  `          {(!isMobile || !rightSidebarCollapsed) && (`,
  `            <RightSidebarArea`,
  `              isMobile={isMobile}`,
  `              rightSidebarCollapsed={rightSidebarCollapsed}`,
  `              rightPanelWidth={rightPanelWidth}`,
  `              setRightPanelWidth={setRightPanelWidth}`,
  `              setRightSidebarCollapsed={setRightSidebarCollapsed}`,
  `              viewTransform={viewTransform}`,
  `              onSetTransform={(t) => {`,
  `                setViewTransform(t);`,
  `                applyTransformToDOM(t);`,
  `              }}`,
  `              canvasWidth={canvasWidth}`,
  `              canvasHeight={canvasHeight}`,
  `              thumbnailCanvas={navigatorCanvasRef.current}`,
  `              thumbnailVersion={navigatorVersion}`,
  `              isFlipped={isFlipped}`,
  `              layers={layers}`,
  `              layerTree={layerTree}`,
  `              activeLayerId={activeLayerId}`,
  `              selectedLayerIds={selectedLayerIds}`,
  `              layerThumbnails={layerThumbnails}`,
  `              onSetActive={(id) => {`,
  `                const clickedLayer = layersRef.current.find(`,
  `                  (l) => l.id === id,`,
  `                );`,
  ``,
  `                // If a move/transform is in progress, commit it to history before switching layers`,
  `                const wasTransformActive =`,
  `                  transformActiveRef.current ||`,
  `                  isDraggingFloatRef.current;`,
  `                if (wasTransformActive && !clickedLayer?.isRuler) {`,
  `                  selectionActionsRef.current.commitFloat({`,
  `                    keepSelection: false,`,
  `                  });`,
  `                }`,
  ``,
  `                if (clickedLayer?.isRuler) {`,
  `                  // Switch to ruler tool when clicking a ruler layer`,
  `                  lastPaintToolRef2.current =`,
  `                    activeToolRef.current !== "ruler"`,
  `                      ? activeToolRef.current`,
  `                      : lastPaintToolRef2.current;`,
  `                  lastPaintLayerIdRef.current =`,
  `                    activeLayerIdRef.current !== id`,
  `                      ? activeLayerIdRef.current`,
  `                      : lastPaintLayerIdRef.current;`,
  `                  // Sync active preset type from the ruler layer`,
  `                  const presetType = (clickedLayer.rulerPresetType ??`,
  `                    "perspective-1pt") as RulerPresetType;`,
  `                  setActiveRulerPresetType(presetType);`,
  `                  activeRulerPresetTypeRef.current = presetType;`,
  `                  setActiveTool("ruler");`,
  `                  setActiveSubpanel("ruler");`,
  `                } else if (activeToolRef.current === "ruler") {`,
  `                  // Switching away from ruler layer: restore paint tool`,
  `                  collapseRulerHistory();`,
  `                  const tool = lastPaintToolRef2.current;`,
  `                  setActiveTool(tool);`,
  `                  if (`,
  `                    tool === "brush" ||`,
  `                    tool === "smudge" ||`,
  `                    tool === "eraser"`,
  `                  ) {`,
  `                    setActiveSubpanel(tool);`,
  `                  } else {`,
  `                    setActiveSubpanel(null);`,
  `                  }`,
  `                }`,
  `                setActiveLayerId(id);`,
  `                activeLayerIdRef.current = id;`,
  `                if (!clickedLayer?.isRuler) {`,
  `                  lastPaintLayerIdRef.current = id;`,
  `                }`,
  ``,
  `                // If a transform was active, begin a new transform on the newly selected layer`,
  `                if (`,
  `                  wasTransformActive &&`,
  `                  !clickedLayer?.isRuler &&`,
  `                  activeToolRef.current === "move"`,
  `                ) {`,
  `                  const newLayerId = id;`,
  `                  const lc = layerCanvasesRef.current.get(newLayerId);`,
  `                  if (lc) {`,
  `                    const ctx = lc.getContext("2d", {`,
  `                      willReadFrequently: !isIPad,`,
  `                    });`,
  `                    if (ctx) {`,
  `                      const imageData = ctx.getImageData(`,
  `                        0,`,
  `                        0,`,
  `                        lc.width,`,
  `                        lc.height,`,
  `                      );`,
  `                      const { data, width, height } = imageData;`,
  `                      let minX = width;`,
  `                      let minY = height;`,
  `                      let maxX = -1;`,
  `                      let maxY = -1;`,
  `                      for (let y = 0; y < height; y++) {`,
  `                        for (let x = 0; x < width; x++) {`,
  `                          const a = data[(y * width + x) * 4 + 3];`,
  `                          if (a > 0) {`,
  `                            if (x < minX) minX = x;`,
  `                            if (x > maxX) maxX = x;`,
  `                            if (y < minY) minY = y;`,
  `                            if (y > maxY) maxY = y;`,
  `                          }`,
  `                        }`,
  `                      }`,
  `                      if (maxX >= minX && maxY >= minY) {`,
  `                        const maskCanvas =`,
  `                          document.createElement("canvas");`,
  `                        maskCanvas.width = canvasWidthRef.current;`,
  `                        maskCanvas.height = canvasHeightRef.current;`,
  `                        const mCtx = maskCanvas.getContext("2d")!;`,
  `                        mCtx.fillStyle = "white";`,
  `                        mCtx.fillRect(`,
  `                          minX,`,
  `                          minY,`,
  `                          maxX - minX + 1,`,
  `                          maxY - minY + 1,`,
  `                        );`,
  `                        selectionMaskRef.current = maskCanvas;`,
  `                        selectionGeometryRef.current = {`,
  `                          type: "rect" as const,`,
  `                          x: minX,`,
  `                          y: minY,`,
  `                          w: maxX - minX + 1,`,
  `                          h: maxY - minY + 1,`,
  `                        };`,
  `                        selectionShapesRef.current = [`,
  `                          selectionGeometryRef.current,`,
  `                        ];`,
  `                        selectionBoundaryPathRef.current.dirty = true;`,
  `                        setSelectionActive(true);`,
  `                        selectionActiveRef.current = true;`,
  `                        selectionActionsRef.current.extractFloat(true);`,
  `                      }`,
  `                    }`,
  `                  }`,
  `                }`,
  `              }}`,
  `              onToggleVisible={(id) => {`,
  `                const layer = layersRef.current.find(`,
  `                  (l) => l.id === id,`,
  `                );`,
  `                if (layer?.isRuler) {`,
  `                  const nowHiding = layer.visible;`,
  `                  const updFn = (l: Layer): Layer => {`,
  `                    if (l.id !== id) return l;`,
  `                    if (nowHiding) {`,
  `                      // Hiding: save current rulerActive state, then turn ruler OFF`,
  `                      return {`,
  `                        ...l,`,
  `                        visible: false,`,
  `                        rulerActiveBeforeHide: l.rulerActive ?? true,`,
  `                        rulerActive: false,`,
  `                      };`,
  `                    }`,
  `                    // Showing: restore previously saved rulerActive state`,
  `                    return {`,
  `                      ...l,`,
  `                      visible: true,`,
  `                      rulerActive:`,
  `                        l.rulerActiveBeforeHide ??`,
  `                        l.rulerActive ??`,
  `                        true,`,
  `                      rulerActiveBeforeHide: undefined,`,
  `                    };`,
  `                  };`,
  `                  setLayers((prev) => prev.map(updFn));`,
  `                  layersRef.current = layersRef.current.map(updFn);`,
  `                  scheduleRulerOverlay();`,
  `                } else {`,
  `                  handleToggleVisible(id);`,
  `                }`,
  `              }}`,
  `              onSetOpacity={handleSetOpacity}`,
  `              onSetBlendMode={handleSetLayerBlendMode}`,
  `              onAddLayer={handleAddLayer}`,
  `              onDeleteLayer={(id) => {`,
  `                const isRuler = layersRef.current.find(`,
  `                  (l) => l.id === id,`,
  `                )?.isRuler;`,
  `                handleDeleteLayer(id);`,
  `                if (isRuler) scheduleRulerOverlay();`,
  `              }}`,
  `              onReorderLayers={handleReorderLayers}`,
  `              onClearLayer={handleClear}`,
  `              onToggleClippingMask={handleToggleClippingMask}`,
  `              onMergeLayers={handleMergeLayers}`,
  `              onRenameLayer={handleRenameLayer}`,
  `              onToggleAlphaLock={handleToggleAlphaLock}`,
  `              onCtrlClickLayer={handleCtrlClickLayer}`,
  `              onToggleRulerActive={(id) => {`,
  `                setLayers((prev) =>`,
  `                  prev.map((l) =>`,
  `                    l.id === id`,
  `                      ? { ...l, rulerActive: !(l.rulerActive ?? true) }`,
  `                      : l,`,
  `                  ),`,
  `                );`,
  `                layersRef.current = layersRef.current.map((l) =>`,
  `                  l.id === id`,
  `                    ? { ...l, rulerActive: !(l.rulerActive ?? true) }`,
  `                    : l,`,
  `                );`,
  `                scheduleRulerOverlay();`,
  `              }}`,
  `              onToggleGroupCollapse={_handleToggleGroupCollapse}`,
  `              onRenameGroup={_handleRenameGroup}`,
  `              onSetGroupOpacity={_handleSetGroupOpacity}`,
  `              onToggleGroupVisible={_handleToggleGroupVisible}`,
  `              onOpenDeleteGroup={(groupId) => {`,
  `                const loc = findNode(layerTreeRef.current, groupId);`,
  `                const groupName =`,
  `                  loc?.node.kind === "group" ? loc.node.name : "Group";`,
  `                setDeleteGroupConfirm({ groupId, groupName });`,
  `              }}`,
  `              onReorderTree={_handleReorderTree}`,
  `              onToggleLayerSelection={_handleToggleLayerSelection}`,
  `              onCreateGroup={handleCreateGroup}`,
  `            />`,
  `          )}{" "}`,
];

// Replace lines 13219–13572 (0-indexed: 13218 to 13571 inclusive)
const before = lines.slice(0, 13218);      // lines 1–13218
const after = lines.slice(13572);          // lines 13573–end

const newContent = [...before, ...replacement, ...after].join("\n");
writeFileSync(filePath, newContent, "utf8");
console.log("Done. New line count:", newContent.split("\n").length);
