/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface HttpHeader { 'value' : string, 'name' : string }
export interface HttpRequest {
  'url' : string,
  'method' : string,
  'body' : Uint8Array,
  'headers' : Array<[string, string]>,
}
export interface HttpRequestResult {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<HttpHeader>,
}
export interface HttpResponse {
  'body' : Uint8Array,
  'headers' : Array<[string, string]>,
  'upgrade' : [] | [boolean],
  'status_code' : number,
}
export interface TransformArgs {
  'context' : Uint8Array,
  'response' : HttpRequestResult,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'addPaymentsAdmin' : ActorMethod<[string], boolean>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  /**
   * / Create a Stripe Checkout session.
   * / - When isSubscription = true: recurring monthly subscription at global price.
   * / - When isSubscription = false: one-time purchase for the given packId.
   * / Returns #ok with the Stripe-hosted URL, or #err with a reason.
   */
  'createCheckoutSession' : ActorMethod<
    [string, string, string, boolean],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCanisterHealth' : ActorMethod<
    [],
    {
      'hasBackendCanisterId' : boolean,
      'hasWebhookSecret' : boolean,
      'deployTimestamp' : bigint,
      'isConfigured' : boolean,
      'hasStripeSecretKey' : boolean,
      'missingConfig' : Array<string>,
      'initWindowOpen' : boolean,
    }
  >,
  'getPackPrices' : ActorMethod<[], Array<[string, bigint]>>,
  'getStripeKeyAudit' : ActorMethod<
    [],
    {
      'webhookSecret' : [] | [{ 'setter' : string, 'timestamp' : bigint }],
      'secretKey' : [] | [{ 'setter' : string, 'timestamp' : bigint }],
    }
  >,
  'getSubscriptionPrice' : ActorMethod<[], bigint>,
  'http_request' : ActorMethod<[HttpRequest], HttpResponse>,
  /**
   * / Update handler for POST /stripe/webhook.
   * / Verifies Stripe HMAC-SHA256 signature on ALL events before processing.
   * / Handles: checkout.session.completed, customer.subscription.created/updated/deleted,
   * / invoice.payment_succeeded.
   */
  'http_request_update' : ActorMethod<[HttpRequest], HttpResponse>,
  'initFromEnv' : ActorMethod<[string], { 'ok' : null } | { 'err' : string }>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listPaymentsAdmins' : ActorMethod<[], Array<string>>,
  'removePaymentsAdmin' : ActorMethod<[string], boolean>,
  'setBackendCanisterId' : ActorMethod<[string], boolean>,
  /**
   * / Set the price (in USD cents) for a purchasable pack. Admin only.
   */
  'setPackPrice' : ActorMethod<
    [string, bigint],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'setStripeSecretKey' : ActorMethod<[string], boolean>,
  'setStripeWebhookSecret' : ActorMethod<[string], boolean>,
  'setSubscriptionPrice' : ActorMethod<
    [bigint],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'transformStripeResponse' : ActorMethod<[TransformArgs], HttpRequestResult>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];