/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ImageReference = IDL.Record({
  'id' : IDL.Text,
  'height' : IDL.Nat,
  'assetUrl' : IDL.Text,
  'width' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ContentType = IDL.Variant({
  'learningmodule' : IDL.Null,
  'referencepack' : IDL.Null,
});
export const ImageSet = IDL.Record({
  'id' : IDL.Text,
  'contentType' : ContentType,
  'name' : IDL.Text,
  'tags' : IDL.Vec(IDL.Text),
  'imageCount' : IDL.Nat,
  'description' : IDL.Text,
  'isFree' : IDL.Bool,
  'previewThumbnail' : IDL.Text,
  'isDefault' : IDL.Bool,
  'isSubscriberContent' : IDL.Bool,
  'priceUsdCents' : IDL.Opt(IDL.Nat),
  'priceICP' : IDL.Opt(IDL.Text),
  'images' : IDL.Vec(ImageReference),
});
export const PublicImageSet = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'imageCount' : IDL.Nat,
  'isFree' : IDL.Bool,
  'previewThumbnail' : IDL.Text,
  'isDefault' : IDL.Bool,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const CanvasSave = IDL.Text;
export const CatalogItem = IDL.Record({
  'id' : IDL.Text,
  'contentType' : ContentType,
  'name' : IDL.Text,
  'imageCount' : IDL.Nat,
  'description' : IDL.Text,
  'isFree' : IDL.Bool,
  'previewThumbnail' : IDL.Text,
  'isSubscriberContent' : IDL.Bool,
  'priceUsdCents' : IDL.Opt(IDL.Nat),
});
export const BrushPreset = IDL.Record({
  'id' : IDL.Text,
  'modifiedAt' : IDL.Int,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'settings' : IDL.Text,
  'isDefault' : IDL.Bool,
});
export const HotkeyAssignments = IDL.Record({
  'assignments' : IDL.Text,
  'modifiedAt' : IDL.Int,
});
export const AppSettings = IDL.Record({
  'uiScale' : IDL.Float64,
  'theme' : IDL.Text,
  'canvasBackground' : IDL.Text,
  'modifiedAt' : IDL.Int,
  'otherSettings' : IDL.Text,
});
export const UserPreferences = IDL.Record({
  'brushes' : IDL.Vec(BrushPreset),
  'hotkeys' : HotkeyAssignments,
  'lastModified' : IDL.Int,
  'settings' : AppSettings,
  'schemaVersion' : IDL.Nat,
});
export const SubscriptionStatus = IDL.Record({
  'active' : IDL.Bool,
  'expiryDateMs' : IDL.Opt(IDL.Nat64),
});
export const SettingsSave = IDL.Text;

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControl' : IDL.Func([], [], []),
  'addAdmin' : IDL.Func([IDL.Principal], [IDL.Bool], []),
  'addImageToSet' : IDL.Func([IDL.Text, ImageReference], [IDL.Bool], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'checkUsernameAvailable' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'createImageSet' : IDL.Func(
      [IDL.Text, IDL.Bool, IDL.Bool, IDL.Opt(IDL.Text)],
      [IDL.Opt(IDL.Text)],
      [],
    ),
  'deleteBrush' : IDL.Func([IDL.Text], [], []),
  'deleteImageSet' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'deleteMascotAnimation' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'deleteMascotExpression' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'getAllImageSetsAdmin' : IDL.Func([], [IDL.Vec(ImageSet)], []),
  'getAllPublicImageSets' : IDL.Func([], [IDL.Vec(PublicImageSet)], ['query']),
  'getAvailableImageSets' : IDL.Func([], [IDL.Vec(ImageSet)], ['query']),
  'getBrushPresets' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCanvasHash' : IDL.Func([], [IDL.Opt(CanvasSave)], ['query']),
  'getFullCatalog' : IDL.Func(
      [],
      [
        IDL.Record({
          'packs' : IDL.Vec(CatalogItem),
          'modules' : IDL.Vec(CatalogItem),
        }),
      ],
      ['query'],
    ),
  'getGuideScript' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
  'getMascotAssets' : IDL.Func(
      [],
      [
        IDL.Record({
          'defaultIdleAnimationName' : IDL.Opt(IDL.Text),
          'animations' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
          'expressions' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
          'defaultExpressionName' : IDL.Opt(IDL.Text),
        }),
      ],
      ['query'],
    ),
  'getModuleScript' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Text)], ['query']),
  'getMyUsername' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
  'getPreferences' : IDL.Func([], [IDL.Opt(UserPreferences)], []),
  'getSchemaVersion' : IDL.Func([], [IDL.Nat], ['query']),
  'getSubscriptionStatus' : IDL.Func([], [SubscriptionStatus], ['query']),
  'getUserEntitlements' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getUserImageSets' : IDL.Func([], [IDL.Vec(ImageSet)], []),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserSettings' : IDL.Func([], [IDL.Opt(SettingsSave)], ['query']),
  'getUsernameForPrincipal' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(IDL.Text)],
      ['query'],
    ),
  'grantEntitlement' : IDL.Func([IDL.Principal, IDL.Text], [IDL.Bool], []),
  'grantPackEntitlement' : IDL.Func([IDL.Principal, IDL.Text], [IDL.Bool], []),
  'grantSubscription' : IDL.Func(
      [IDL.Principal, IDL.Text, IDL.Nat64],
      [IDL.Bool],
      [],
    ),
  'isAdmin' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isEntitledTo' : IDL.Func([IDL.Principal, IDL.Text], [IDL.Bool], ['query']),
  'registerUsername' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'removeAdmin' : IDL.Func([IDL.Principal], [IDL.Bool], []),
  'removeImageFromSet' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'renameSet' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'revokeEntitlement' : IDL.Func([IDL.Principal, IDL.Text], [IDL.Bool], []),
  'revokeSubscription' : IDL.Func([IDL.Principal], [IDL.Bool], []),
  'saveBrush' : IDL.Func([BrushPreset], [], []),
  'saveBrushPresets' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveCanvasHash' : IDL.Func([CanvasSave], [], []),
  'saveGuideScript' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'saveModuleScript' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'savePreferences' : IDL.Func([UserPreferences], [], []),
  'saveUserSettings' : IDL.Func([SettingsSave], [], []),
  'setContentType' : IDL.Func([IDL.Text, ContentType], [IDL.Bool], []),
  'setDefaultExpression' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'setDefaultIdleAnimation' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'setDescription' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'setImageSetDefault' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'setImageSetPrice' : IDL.Func([IDL.Text, IDL.Opt(IDL.Text)], [IDL.Bool], []),
  'setPaymentsCanisterPrincipal' : IDL.Func([IDL.Principal], [IDL.Bool], []),
  'setPriceUsdCents' : IDL.Func([IDL.Text, IDL.Opt(IDL.Nat)], [IDL.Bool], []),
  'setSubscriberContent' : IDL.Func([IDL.Text, IDL.Bool], [IDL.Bool], []),
  'updateSetTags' : IDL.Func([IDL.Text, IDL.Vec(IDL.Text)], [IDL.Bool], []),
  'updateSubscriptionExpiry' : IDL.Func(
      [IDL.Principal, IDL.Nat64],
      [IDL.Bool],
      [],
    ),
  'uploadMascotAnimation' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'uploadMascotExpression' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ImageReference = IDL.Record({
    'id' : IDL.Text,
    'height' : IDL.Nat,
    'assetUrl' : IDL.Text,
    'width' : IDL.Nat,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ContentType = IDL.Variant({
    'learningmodule' : IDL.Null,
    'referencepack' : IDL.Null,
  });
  const ImageSet = IDL.Record({
    'id' : IDL.Text,
    'contentType' : ContentType,
    'name' : IDL.Text,
    'tags' : IDL.Vec(IDL.Text),
    'imageCount' : IDL.Nat,
    'description' : IDL.Text,
    'isFree' : IDL.Bool,
    'previewThumbnail' : IDL.Text,
    'isDefault' : IDL.Bool,
    'isSubscriberContent' : IDL.Bool,
    'priceUsdCents' : IDL.Opt(IDL.Nat),
    'priceICP' : IDL.Opt(IDL.Text),
    'images' : IDL.Vec(ImageReference),
  });
  const PublicImageSet = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'imageCount' : IDL.Nat,
    'isFree' : IDL.Bool,
    'previewThumbnail' : IDL.Text,
    'isDefault' : IDL.Bool,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const CanvasSave = IDL.Text;
  const CatalogItem = IDL.Record({
    'id' : IDL.Text,
    'contentType' : ContentType,
    'name' : IDL.Text,
    'imageCount' : IDL.Nat,
    'description' : IDL.Text,
    'isFree' : IDL.Bool,
    'previewThumbnail' : IDL.Text,
    'isSubscriberContent' : IDL.Bool,
    'priceUsdCents' : IDL.Opt(IDL.Nat),
  });
  const BrushPreset = IDL.Record({
    'id' : IDL.Text,
    'modifiedAt' : IDL.Int,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'settings' : IDL.Text,
    'isDefault' : IDL.Bool,
  });
  const HotkeyAssignments = IDL.Record({
    'assignments' : IDL.Text,
    'modifiedAt' : IDL.Int,
  });
  const AppSettings = IDL.Record({
    'uiScale' : IDL.Float64,
    'theme' : IDL.Text,
    'canvasBackground' : IDL.Text,
    'modifiedAt' : IDL.Int,
    'otherSettings' : IDL.Text,
  });
  const UserPreferences = IDL.Record({
    'brushes' : IDL.Vec(BrushPreset),
    'hotkeys' : HotkeyAssignments,
    'lastModified' : IDL.Int,
    'settings' : AppSettings,
    'schemaVersion' : IDL.Nat,
  });
  const SubscriptionStatus = IDL.Record({
    'active' : IDL.Bool,
    'expiryDateMs' : IDL.Opt(IDL.Nat64),
  });
  const SettingsSave = IDL.Text;
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControl' : IDL.Func([], [], []),
    'addAdmin' : IDL.Func([IDL.Principal], [IDL.Bool], []),
    'addImageToSet' : IDL.Func([IDL.Text, ImageReference], [IDL.Bool], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'checkUsernameAvailable' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'createImageSet' : IDL.Func(
        [IDL.Text, IDL.Bool, IDL.Bool, IDL.Opt(IDL.Text)],
        [IDL.Opt(IDL.Text)],
        [],
      ),
    'deleteBrush' : IDL.Func([IDL.Text], [], []),
    'deleteImageSet' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'deleteMascotAnimation' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'deleteMascotExpression' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'getAllImageSetsAdmin' : IDL.Func([], [IDL.Vec(ImageSet)], []),
    'getAllPublicImageSets' : IDL.Func(
        [],
        [IDL.Vec(PublicImageSet)],
        ['query'],
      ),
    'getAvailableImageSets' : IDL.Func([], [IDL.Vec(ImageSet)], ['query']),
    'getBrushPresets' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCanvasHash' : IDL.Func([], [IDL.Opt(CanvasSave)], ['query']),
    'getFullCatalog' : IDL.Func(
        [],
        [
          IDL.Record({
            'packs' : IDL.Vec(CatalogItem),
            'modules' : IDL.Vec(CatalogItem),
          }),
        ],
        ['query'],
      ),
    'getGuideScript' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
    'getMascotAssets' : IDL.Func(
        [],
        [
          IDL.Record({
            'defaultIdleAnimationName' : IDL.Opt(IDL.Text),
            'animations' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
            'expressions' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
            'defaultExpressionName' : IDL.Opt(IDL.Text),
          }),
        ],
        ['query'],
      ),
    'getModuleScript' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Text)], ['query']),
    'getMyUsername' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
    'getPreferences' : IDL.Func([], [IDL.Opt(UserPreferences)], []),
    'getSchemaVersion' : IDL.Func([], [IDL.Nat], ['query']),
    'getSubscriptionStatus' : IDL.Func([], [SubscriptionStatus], ['query']),
    'getUserEntitlements' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getUserImageSets' : IDL.Func([], [IDL.Vec(ImageSet)], []),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserSettings' : IDL.Func([], [IDL.Opt(SettingsSave)], ['query']),
    'getUsernameForPrincipal' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(IDL.Text)],
        ['query'],
      ),
    'grantEntitlement' : IDL.Func([IDL.Principal, IDL.Text], [IDL.Bool], []),
    'grantPackEntitlement' : IDL.Func(
        [IDL.Principal, IDL.Text],
        [IDL.Bool],
        [],
      ),
    'grantSubscription' : IDL.Func(
        [IDL.Principal, IDL.Text, IDL.Nat64],
        [IDL.Bool],
        [],
      ),
    'isAdmin' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isEntitledTo' : IDL.Func([IDL.Principal, IDL.Text], [IDL.Bool], ['query']),
    'registerUsername' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'removeAdmin' : IDL.Func([IDL.Principal], [IDL.Bool], []),
    'removeImageFromSet' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'renameSet' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'revokeEntitlement' : IDL.Func([IDL.Principal, IDL.Text], [IDL.Bool], []),
    'revokeSubscription' : IDL.Func([IDL.Principal], [IDL.Bool], []),
    'saveBrush' : IDL.Func([BrushPreset], [], []),
    'saveBrushPresets' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveCanvasHash' : IDL.Func([CanvasSave], [], []),
    'saveGuideScript' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'saveModuleScript' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'savePreferences' : IDL.Func([UserPreferences], [], []),
    'saveUserSettings' : IDL.Func([SettingsSave], [], []),
    'setContentType' : IDL.Func([IDL.Text, ContentType], [IDL.Bool], []),
    'setDefaultExpression' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'setDefaultIdleAnimation' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'setDescription' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'setImageSetDefault' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'setImageSetPrice' : IDL.Func(
        [IDL.Text, IDL.Opt(IDL.Text)],
        [IDL.Bool],
        [],
      ),
    'setPaymentsCanisterPrincipal' : IDL.Func([IDL.Principal], [IDL.Bool], []),
    'setPriceUsdCents' : IDL.Func([IDL.Text, IDL.Opt(IDL.Nat)], [IDL.Bool], []),
    'setSubscriberContent' : IDL.Func([IDL.Text, IDL.Bool], [IDL.Bool], []),
    'updateSetTags' : IDL.Func([IDL.Text, IDL.Vec(IDL.Text)], [IDL.Bool], []),
    'updateSubscriptionExpiry' : IDL.Func(
        [IDL.Principal, IDL.Nat64],
        [IDL.Bool],
        [],
      ),
    'uploadMascotAnimation' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'uploadMascotExpression' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };