/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const CanvasSave = IDL.Text;
export const BrushPreset = IDL.Record({
  'id' : IDL.Text,
  'modifiedAt' : IDL.Int,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'settings' : IDL.Text,
  'isDefault' : IDL.Bool,
});
export const HotkeyAssignments = IDL.Record({
  'assignments' : IDL.Text,
  'modifiedAt' : IDL.Int,
});
export const AppSettings = IDL.Record({
  'uiScale' : IDL.Float64,
  'theme' : IDL.Text,
  'canvasBackground' : IDL.Text,
  'modifiedAt' : IDL.Int,
  'otherSettings' : IDL.Text,
});
export const UserPreferences = IDL.Record({
  'brushes' : IDL.Vec(BrushPreset),
  'hotkeys' : HotkeyAssignments,
  'lastModified' : IDL.Int,
  'settings' : AppSettings,
  'schemaVersion' : IDL.Nat,
});
export const SettingsSave = IDL.Text;

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControl' : IDL.Func([], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteBrush' : IDL.Func([IDL.Text], [], []),
  'getBrushPresets' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCanvasHash' : IDL.Func([], [IDL.Opt(CanvasSave)], ['query']),
  'getPreferences' : IDL.Func([], [IDL.Opt(UserPreferences)], ['query']),
  'getSchemaVersion' : IDL.Func([], [IDL.Nat], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserSettings' : IDL.Func([], [IDL.Opt(SettingsSave)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveBrush' : IDL.Func([BrushPreset], [], []),
  'saveBrushPresets' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveCanvasHash' : IDL.Func([CanvasSave], [], []),
  'savePreferences' : IDL.Func([UserPreferences], [], []),
  'saveUserSettings' : IDL.Func([SettingsSave], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const CanvasSave = IDL.Text;
  const BrushPreset = IDL.Record({
    'id' : IDL.Text,
    'modifiedAt' : IDL.Int,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'settings' : IDL.Text,
    'isDefault' : IDL.Bool,
  });
  const HotkeyAssignments = IDL.Record({
    'assignments' : IDL.Text,
    'modifiedAt' : IDL.Int,
  });
  const AppSettings = IDL.Record({
    'uiScale' : IDL.Float64,
    'theme' : IDL.Text,
    'canvasBackground' : IDL.Text,
    'modifiedAt' : IDL.Int,
    'otherSettings' : IDL.Text,
  });
  const UserPreferences = IDL.Record({
    'brushes' : IDL.Vec(BrushPreset),
    'hotkeys' : HotkeyAssignments,
    'lastModified' : IDL.Int,
    'settings' : AppSettings,
    'schemaVersion' : IDL.Nat,
  });
  const SettingsSave = IDL.Text;
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControl' : IDL.Func([], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteBrush' : IDL.Func([IDL.Text], [], []),
    'getBrushPresets' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCanvasHash' : IDL.Func([], [IDL.Opt(CanvasSave)], ['query']),
    'getPreferences' : IDL.Func([], [IDL.Opt(UserPreferences)], ['query']),
    'getSchemaVersion' : IDL.Func([], [IDL.Nat], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserSettings' : IDL.Func([], [IDL.Opt(SettingsSave)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveBrush' : IDL.Func([BrushPreset], [], []),
    'saveBrushPresets' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveCanvasHash' : IDL.Func([CanvasSave], [], []),
    'savePreferences' : IDL.Func([UserPreferences], [], []),
    'saveUserSettings' : IDL.Func([SettingsSave], [], []),
  });
};

export const init = ({ IDL }) => { return []; };