/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface HttpRequest {
  'url' : string,
  'method' : string,
  'body' : Uint8Array,
  'headers' : Array<[string, string]>,
}
export interface HttpResponse {
  'body' : Uint8Array,
  'headers' : Array<[string, string]>,
  'upgrade' : [] | [boolean],
  'status_code' : number,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  /**
   * / Create a Stripe Checkout session for a given pack.
   * / - Rejects anonymous callers.
   * / - Uses ICP HTTPS outcalls to POST to the Stripe API.
   * / - Stores the session → (principal, itemType, itemId) mapping.
   * / - Returns the Stripe-hosted Checkout URL on success.
   * / - successUrl and cancelUrl must be provided by the frontend (window.location.origin-based).
   */
  'createCheckoutSession' : ActorMethod<
    [string, string, string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  /**
   * / Return all pack IDs and their current prices (USD cents). Public.
   */
  'getPackPrices' : ActorMethod<[], Array<[string, bigint]>>,
  /**
   * / Standard ICP HTTP query handler.
   * / For POST /stripe/webhook, upgrades to http_request_update.
   */
  'http_request' : ActorMethod<[HttpRequest], HttpResponse>,
  /**
   * / Update handler for POST /stripe/webhook.
   * / - Verifies HMAC-SHA256 Stripe signature.
   * / - Handles checkout.session.completed events.
   * / - Idempotency: skips already-processed sessions.
   * / - Calls imageSets canister to grant entitlement to buyer.
   * / - Returns HTTP 200 on success, 400/500 on failure.
   */
  'http_request_update' : ActorMethod<[HttpRequest], HttpResponse>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  /**
   * / Set the price (in USD cents) for a purchasable pack. Admin only.
   */
  'setPackPrice' : ActorMethod<[string, bigint], boolean>,
  /**
   * / Store the Stripe secret key. Admin only. Write-only — never returned.
   */
  'setStripeSecretKey' : ActorMethod<[string], boolean>,
  /**
   * / Store the Stripe webhook signing secret. Admin only. Write-only — never returned.
   */
  'setStripeWebhookSecret' : ActorMethod<[string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];