/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface UserPreferences {
    brushes: Array<BrushPreset>;
    hotkeys: HotkeyAssignments;
    lastModified: bigint;
    settings: AppSettings;
    schemaVersion: bigint;
}
export interface _ImmutableObjectStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface PublicImageSet {
    id: string;
    name: string;
    imageCount: bigint;
    isFree: boolean;
    previewThumbnail: string;
    isDefault: boolean;
}
export interface _ImmutableObjectStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface ImageReference {
    id: string;
    height: bigint;
    assetUrl: string;
    width: bigint;
}
export interface HotkeyAssignments {
    assignments: string;
    modifiedAt: bigint;
}
export type CanvasSave = string;
export interface AppSettings {
    uiScale: number;
    theme: string;
    canvasBackground: string;
    modifiedAt: bigint;
    otherSettings: string;
}
export interface _ImmutableObjectStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export type SettingsSave = string;
export interface BrushPreset {
    id: string;
    modifiedAt: bigint;
    name: string;
    createdAt: bigint;
    settings: string;
    isDefault: boolean;
}
export interface CatalogItem {
    id: string;
    contentType: ContentType;
    name: string;
    imageCount: bigint;
    description: string;
    isFree: boolean;
    previewThumbnail: string;
    isSubscriberContent: boolean;
    priceUsdCents?: bigint;
}
export interface SubscriptionStatus {
    active: boolean;
    expiryDateMs?: bigint;
}
export interface UserProfile {
    name: string;
}
export interface ImageSet {
    id: string;
    contentType: ContentType;
    name: string;
    tags: Array<string>;
    imageCount: bigint;
    description: string;
    isFree: boolean;
    previewThumbnail: string;
    isDefault: boolean;
    isSubscriberContent: boolean;
    priceUsdCents?: bigint;
    priceICP?: string;
    images: Array<ImageReference>;
}
export enum ContentType {
    learningmodule = "learningmodule",
    referencepack = "referencepack"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _immutableObjectStorageBlobsAreLive(hashes: Array<Uint8Array>): Promise<Array<boolean>>;
    _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _immutableObjectStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _immutableObjectStorageCreateCertificate(blobHash: string): Promise<_ImmutableObjectStorageCreateCertificateResult>;
    _immutableObjectStorageRefillCashier(refillInformation: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult>;
    _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControl(): Promise<void>;
    /**
     * / Adds a new admin. Only an existing admin may call this.
     * / Returns false if the caller is not an admin.
     */
    addAdmin(newAdmin: Principal): Promise<boolean>;
    /**
     * / Admin only — add an image reference to a set.
     * / Returns false if caller is not admin or setId doesn't exist.
     */
    addImageToSet(setId: string, image: ImageReference): Promise<boolean>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    /**
     * / Returns true if the username is not yet taken — free query call.
     */
    checkUsernameAvailable(username: string): Promise<boolean>;
    /**
     * / Admin only — create a new image set.
     * / Returns the new set's ID on success, null if caller is not admin or
     * / name is invalid (must be 3–50 characters).
     * / If isFree is true, priceICP is ignored and stored as null.
     * / If isDefault is true, all other sets are unset as default.
     */
    createImageSet(name: string, isFree: boolean, isDefault: boolean, priceICP: string | null): Promise<string | null>;
    deleteBrush(id: string): Promise<void>;
    /**
     * / Admin only — delete an entire image set.
     * / Cannot delete default sets (isDefault == true).
     * / Returns false if caller is not admin, setId doesn't exist, or set is a default.
     */
    deleteImageSet(setId: string): Promise<boolean>;
    /**
     * / Admin only — remove an animation from the mascot registry.
     * / If the deleted animation was the default idle, clears defaultIdleAnimationName.
     * / Returns true on success, false if caller is not admin or name not found.
     */
    deleteMascotAnimation(name: string): Promise<boolean>;
    /**
     * / Admin only — remove an expression from the mascot registry.
     * / If the deleted expression was the default, clears defaultExpressionName.
     * / Returns true on success, false if caller is not admin or name not found.
     */
    deleteMascotExpression(name: string): Promise<boolean>;
    /**
     * / Admin only — get all image sets including paid ones, for admin management UI.
     * / Returns an empty array if caller is not admin.
     * / Uses an update call (not query) so it can run ensureStarterSetsCleared()
     * / to strip any legacy dummy placeholder images on first access after a deploy.
     */
    getAllImageSetsAdmin(): Promise<Array<ImageSet>>;
    /**
     * / Public query — returns ALL image sets as catalog entries (no images array).
     * / Used by the marketplace to build the full grid so users can see and purchase
     * / packs they do not yet own. Diff against getAvailableImageSets() for owned state.
     */
    getAllPublicImageSets(): Promise<Array<PublicImageSet>>;
    /**
     * / Public query — returns all free sets plus sets the caller has purchased entitlements for.
     * / Also includes subscriber-tagged sets if the caller has an active subscription.
     */
    getAvailableImageSets(): Promise<Array<ImageSet>>;
    getBrushPresets(): Promise<string | null>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCanvasHash(): Promise<CanvasSave | null>;
    getFullCatalog(): Promise<{
        packs: Array<CatalogItem>;
        modules: Array<CatalogItem>;
    }>;
    /**
     * / Public query — returns the in-app guide script, or null if not yet set.
     * / Equivalent to getModuleScript("guide").
     */
    getGuideScript(): Promise<string | null>;
    /**
     * / Public query — returns all mascot registry data: expressions, animations, and defaults.
     * / Returns empty arrays and null defaults if nothing has been uploaded yet.
     */
    getMascotAssets(): Promise<{
        defaultIdleAnimationName?: string;
        animations: Array<[string, string]>;
        expressions: Array<[string, string]>;
        defaultExpressionName?: string;
    }>;
    /**
     * / Public query — returns the script text for a module, or null if not stored.
     */
    getModuleScript(moduleId: string): Promise<string | null>;
    /**
     * / Returns the username for the caller's principal, or null if none registered.
     */
    getMyUsername(): Promise<string | null>;
    getPreferences(): Promise<UserPreferences | null>;
    getSchemaVersion(): Promise<bigint>;
    /**
     * / Adds a new admin. Only an existing admin may call this.
     * / Returns false if the caller is not an admin.
     */
    getSubscriptionStatus(): Promise<SubscriptionStatus>;
    /**
     * / Returns the set IDs the caller has been explicitly granted.
     */
    getUserEntitlements(): Promise<Array<string>>;
    /**
     * / Returns all default image sets plus any sets the caller has been granted.
     */
    getUserImageSets(): Promise<Array<ImageSet>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getUserSettings(): Promise<SettingsSave | null>;
    /**
     * / Returns the username for any given principal — for display purposes.
     */
    getUsernameForPrincipal(p: Principal): Promise<string | null>;
    /**
     * / Admin: grant a set to a principal. Returns false if the set does not exist.
     */
    grantEntitlement(principal: Principal, setId: string): Promise<boolean>;
    /**
     * / Called by the payments canister to grant a pack entitlement to a user.
     * / Only the stored payments canister principal is allowed to call this.
     * / Idempotent — adding an entitlement the user already has is a no-op.
     * / Returns false if the caller is not the trusted payments canister,
     * / if no payments canister principal has been configured, or if the
     * / pack does not exist in the image set registry.
     */
    grantPackEntitlement(userPrincipal: Principal, packId: string): Promise<boolean>;
    grantSubscription(userPrincipal: Principal, stripeSubId: string, expiryDateMs: bigint): Promise<boolean>;
    /**
     * / Returns true if the given principal is in the admin set.
     * / Safe as a query because isAdminPrincipal() never mutates state.
     */
    isAdmin(p: Principal): Promise<boolean>;
    isCallerAdmin(): Promise<boolean>;
    isEntitledTo(userPrincipal: Principal, packId: string): Promise<boolean>;
    /**
     * / Registers a username for the caller's principal.
     * / Returns true on success, false if the caller already has a username
     * / or if the username is already taken (race condition guard).
     */
    registerUsername(username: string): Promise<boolean>;
    /**
     * / Removes an admin. Only an existing admin may call this.
     * / Returns false if the caller is not an admin or if the caller tries
     * / to remove themselves.
     */
    removeAdmin(target: Principal): Promise<boolean>;
    /**
     * / Admin only — remove an image reference from a set.
     * / Returns false if caller is not admin, setId doesn't exist, or imageId not found.
     */
    removeImageFromSet(setId: string, imageId: string): Promise<boolean>;
    /**
     * / Admin only — rename an image set.
     * / newName must not be empty. Returns false if caller is not admin,
     * / setId doesn't exist, or newName is empty.
     */
    renameSet(setId: string, newName: string): Promise<boolean>;
    /**
     * / Admin: revoke a set from a principal. Returns false if the set does not exist.
     */
    revokeEntitlement(principal: Principal, setId: string): Promise<boolean>;
    revokeSubscription(userPrincipal: Principal): Promise<boolean>;
    saveBrush(brush: BrushPreset): Promise<void>;
    saveBrushPresets(data: string): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    saveCanvasHash(canvasHash: CanvasSave): Promise<void>;
    /**
     * / Admin only — save or overwrite the in-app guide dialogue script.
     * / Equivalent to saveModuleScript("guide", scriptText).
     * / Returns true on success, false if caller is not admin.
     */
    saveGuideScript(scriptText: string): Promise<boolean>;
    /**
     * / Admin only — save or overwrite the dialogue script for a module.
     * / Module IDs are simple strings like "figure-drawing" or "still-life".
     * / Use moduleId = "guide" to set the in-app guide script.
     * / Returns true on success, false if caller is not admin.
     */
    saveModuleScript(moduleId: string, scriptText: string): Promise<boolean>;
    savePreferences(prefs: UserPreferences): Promise<void>;
    saveUserSettings(settings: SettingsSave): Promise<void>;
    setContentType(setId: string, contentType: ContentType): Promise<boolean>;
    /**
     * / Admin only — set the default expression name.
     * / Returns false if no expression with that name exists or caller is not admin.
     */
    setDefaultExpression(name: string): Promise<boolean>;
    /**
     * / Admin only — set the default idle animation name.
     * / Returns false if no animation with that name exists or caller is not admin.
     */
    setDefaultIdleAnimation(name: string): Promise<boolean>;
    setDescription(setId: string, description: string): Promise<boolean>;
    /**
     * / Admin only — mark a set as the sole default set.
     * / Unsets isDefault on all other sets. Returns false if caller is not admin
     * / or the setId does not exist.
     */
    setImageSetDefault(setId: string): Promise<boolean>;
    /**
     * / Admin only — set or clear the price of a set.
     * / Pass null to clear the price (make free). Returns false if caller is not admin
     * / or the setId does not exist.
     */
    setImageSetPrice(setId: string, priceICP: string | null): Promise<boolean>;
    /**
     * / Admin only — store the trusted payments canister principal.
     * / grantPackEntitlement will only accept calls from this principal.
     * / Returns false if the caller is not an admin.
     */
    setPaymentsCanisterPrincipal(p: Principal): Promise<boolean>;
    setPriceUsdCents(setId: string, priceUsdCents: bigint | null): Promise<boolean>;
    setSubscriberContent(setId: string, isSubscriberContent: boolean): Promise<boolean>;
    /**
     * / Admin only — update the tags for an image set.
     * / All tags are normalized to lowercase before storing.
     * / Returns false if caller is not admin or setId doesn't exist.
     */
    updateSetTags(setId: string, tags: Array<string>): Promise<boolean>;
    updateSubscriptionExpiry(userPrincipal: Principal, newExpiryMs: bigint): Promise<boolean>;
    /**
     * / Admin only — add or replace an animation (Lottie JSON) in the mascot registry.
     * / If an animation with the same name already exists, its blobUrl is replaced.
     * / Returns true on success, false if caller is not admin.
     */
    uploadMascotAnimation(name: string, blobUrl: string): Promise<boolean>;
    /**
     * / Admin only — add or replace an expression (PNG) in the mascot registry.
     * / If an expression with the same name already exists, its blobUrl is replaced.
     * / Returns true on success, false if caller is not admin.
     */
    uploadMascotExpression(name: string, blobUrl: string): Promise<boolean>;
}
import type { CanvasSave as _CanvasSave, CatalogItem as _CatalogItem, ContentType as _ContentType, ImageReference as _ImageReference, ImageSet as _ImageSet, SettingsSave as _SettingsSave, SubscriptionStatus as _SubscriptionStatus, UserPreferences as _UserPreferences, UserProfile as _UserProfile, UserRole as _UserRole, _ImmutableObjectStorageRefillInformation as __ImmutableObjectStorageRefillInformation, _ImmutableObjectStorageRefillResult as __ImmutableObjectStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _immutableObjectStorageBlobsAreLive(arg0: Array<Uint8Array>): Promise<Array<boolean>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
            return result;
        }
    }
    async _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsToDelete();
            return result;
        }
    }
    async _immutableObjectStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _immutableObjectStorageCreateCertificate(arg0: string): Promise<_ImmutableObjectStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _immutableObjectStorageRefillCashier(arg0: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControl();
            return result;
        }
    }
    async addAdmin(arg0: Principal): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.addAdmin(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addAdmin(arg0);
            return result;
        }
    }
    async addImageToSet(arg0: string, arg1: ImageReference): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.addImageToSet(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addImageToSet(arg0, arg1);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async checkUsernameAvailable(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.checkUsernameAvailable(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.checkUsernameAvailable(arg0);
            return result;
        }
    }
    async createImageSet(arg0: string, arg1: boolean, arg2: boolean, arg3: string | null): Promise<string | null> {
        if (this.processError) {
            try {
                const result = await this.actor.createImageSet(arg0, arg1, arg2, to_candid_opt_n10(this._uploadFile, this._downloadFile, arg3));
                return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createImageSet(arg0, arg1, arg2, to_candid_opt_n10(this._uploadFile, this._downloadFile, arg3));
            return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteBrush(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteBrush(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteBrush(arg0);
            return result;
        }
    }
    async deleteImageSet(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteImageSet(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteImageSet(arg0);
            return result;
        }
    }
    async deleteMascotAnimation(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteMascotAnimation(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteMascotAnimation(arg0);
            return result;
        }
    }
    async deleteMascotExpression(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteMascotExpression(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteMascotExpression(arg0);
            return result;
        }
    }
    async getAllImageSetsAdmin(): Promise<Array<ImageSet>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllImageSetsAdmin();
                return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllImageSetsAdmin();
            return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllPublicImageSets(): Promise<Array<PublicImageSet>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPublicImageSets();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPublicImageSets();
            return result;
        }
    }
    async getAvailableImageSets(): Promise<Array<ImageSet>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAvailableImageSets();
                return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAvailableImageSets();
            return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBrushPresets(): Promise<string | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getBrushPresets();
                return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBrushPresets();
            return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCanvasHash(): Promise<CanvasSave | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCanvasHash();
                return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCanvasHash();
            return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFullCatalog(): Promise<{
        packs: Array<CatalogItem>;
        modules: Array<CatalogItem>;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getFullCatalog();
                return from_candid_record_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFullCatalog();
            return from_candid_record_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getGuideScript(): Promise<string | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getGuideScript();
                return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGuideScript();
            return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMascotAssets(): Promise<{
        defaultIdleAnimationName?: string;
        animations: Array<[string, string]>;
        expressions: Array<[string, string]>;
        defaultExpressionName?: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getMascotAssets();
                return from_candid_record_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMascotAssets();
            return from_candid_record_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getModuleScript(arg0: string): Promise<string | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getModuleScript(arg0);
                return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getModuleScript(arg0);
            return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyUsername(): Promise<string | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyUsername();
                return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyUsername();
            return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPreferences(): Promise<UserPreferences | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPreferences();
                return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPreferences();
            return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSchemaVersion(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getSchemaVersion();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSchemaVersion();
            return result;
        }
    }
    async getSubscriptionStatus(): Promise<SubscriptionStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.getSubscriptionStatus();
                return from_candid_SubscriptionStatus_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSubscriptionStatus();
            return from_candid_SubscriptionStatus_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserEntitlements(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserEntitlements();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserEntitlements();
            return result;
        }
    }
    async getUserImageSets(): Promise<Array<ImageSet>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserImageSets();
                return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserImageSets();
            return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserSettings(): Promise<SettingsSave | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserSettings();
                return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserSettings();
            return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUsernameForPrincipal(arg0: Principal): Promise<string | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUsernameForPrincipal(arg0);
                return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUsernameForPrincipal(arg0);
            return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async grantEntitlement(arg0: Principal, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.grantEntitlement(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.grantEntitlement(arg0, arg1);
            return result;
        }
    }
    async grantPackEntitlement(arg0: Principal, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.grantPackEntitlement(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.grantPackEntitlement(arg0, arg1);
            return result;
        }
    }
    async grantSubscription(arg0: Principal, arg1: string, arg2: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.grantSubscription(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.grantSubscription(arg0, arg1, arg2);
            return result;
        }
    }
    async isAdmin(arg0: Principal): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isAdmin(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isAdmin(arg0);
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isEntitledTo(arg0: Principal, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isEntitledTo(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isEntitledTo(arg0, arg1);
            return result;
        }
    }
    async registerUsername(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.registerUsername(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerUsername(arg0);
            return result;
        }
    }
    async removeAdmin(arg0: Principal): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.removeAdmin(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeAdmin(arg0);
            return result;
        }
    }
    async removeImageFromSet(arg0: string, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.removeImageFromSet(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeImageFromSet(arg0, arg1);
            return result;
        }
    }
    async renameSet(arg0: string, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.renameSet(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.renameSet(arg0, arg1);
            return result;
        }
    }
    async revokeEntitlement(arg0: Principal, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.revokeEntitlement(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.revokeEntitlement(arg0, arg1);
            return result;
        }
    }
    async revokeSubscription(arg0: Principal): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.revokeSubscription(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.revokeSubscription(arg0);
            return result;
        }
    }
    async saveBrush(arg0: BrushPreset): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveBrush(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveBrush(arg0);
            return result;
        }
    }
    async saveBrushPresets(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveBrushPresets(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveBrushPresets(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async saveCanvasHash(arg0: CanvasSave): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCanvasHash(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCanvasHash(arg0);
            return result;
        }
    }
    async saveGuideScript(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.saveGuideScript(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveGuideScript(arg0);
            return result;
        }
    }
    async saveModuleScript(arg0: string, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.saveModuleScript(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveModuleScript(arg0, arg1);
            return result;
        }
    }
    async savePreferences(arg0: UserPreferences): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.savePreferences(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.savePreferences(arg0);
            return result;
        }
    }
    async saveUserSettings(arg0: SettingsSave): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveUserSettings(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveUserSettings(arg0);
            return result;
        }
    }
    async setContentType(arg0: string, arg1: ContentType): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.setContentType(arg0, to_candid_ContentType_n31(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setContentType(arg0, to_candid_ContentType_n31(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async setDefaultExpression(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.setDefaultExpression(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setDefaultExpression(arg0);
            return result;
        }
    }
    async setDefaultIdleAnimation(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.setDefaultIdleAnimation(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setDefaultIdleAnimation(arg0);
            return result;
        }
    }
    async setDescription(arg0: string, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.setDescription(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setDescription(arg0, arg1);
            return result;
        }
    }
    async setImageSetDefault(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.setImageSetDefault(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setImageSetDefault(arg0);
            return result;
        }
    }
    async setImageSetPrice(arg0: string, arg1: string | null): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.setImageSetPrice(arg0, to_candid_opt_n10(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setImageSetPrice(arg0, to_candid_opt_n10(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async setPaymentsCanisterPrincipal(arg0: Principal): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.setPaymentsCanisterPrincipal(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setPaymentsCanisterPrincipal(arg0);
            return result;
        }
    }
    async setPriceUsdCents(arg0: string, arg1: bigint | null): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.setPriceUsdCents(arg0, to_candid_opt_n33(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setPriceUsdCents(arg0, to_candid_opt_n33(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async setSubscriberContent(arg0: string, arg1: boolean): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.setSubscriberContent(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setSubscriberContent(arg0, arg1);
            return result;
        }
    }
    async updateSetTags(arg0: string, arg1: Array<string>): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSetTags(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSetTags(arg0, arg1);
            return result;
        }
    }
    async updateSubscriptionExpiry(arg0: Principal, arg1: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSubscriptionExpiry(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSubscriptionExpiry(arg0, arg1);
            return result;
        }
    }
    async uploadMascotAnimation(arg0: string, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadMascotAnimation(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadMascotAnimation(arg0, arg1);
            return result;
        }
    }
    async uploadMascotExpression(arg0: string, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadMascotExpression(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadMascotExpression(arg0, arg1);
            return result;
        }
    }
}
function from_candid_CatalogItem_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CatalogItem): CatalogItem {
    return from_candid_record_n24(_uploadFile, _downloadFile, value);
}
function from_candid_ContentType_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ContentType): ContentType {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid_ImageSet_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImageSet): ImageSet {
    return from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid_SubscriptionStatus_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SubscriptionStatus): SubscriptionStatus {
    return from_candid_record_n28(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function from_candid__ImmutableObjectStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __ImmutableObjectStorageRefillResult): _ImmutableObjectStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_CanvasSave]): CanvasSave | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserPreferences]): UserPreferences | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_SettingsSave]): SettingsSave | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    contentType: _ContentType;
    name: string;
    tags: Array<string>;
    imageCount: bigint;
    description: string;
    isFree: boolean;
    previewThumbnail: string;
    isDefault: boolean;
    isSubscriberContent: boolean;
    priceUsdCents: [] | [bigint];
    priceICP: [] | [string];
    images: Array<_ImageReference>;
}): {
    id: string;
    contentType: ContentType;
    name: string;
    tags: Array<string>;
    imageCount: bigint;
    description: string;
    isFree: boolean;
    previewThumbnail: string;
    isDefault: boolean;
    isSubscriberContent: boolean;
    priceUsdCents?: bigint;
    priceICP?: string;
    images: Array<ImageReference>;
} {
    return {
        id: value.id,
        contentType: from_candid_ContentType_n15(_uploadFile, _downloadFile, value.contentType),
        name: value.name,
        tags: value.tags,
        imageCount: value.imageCount,
        description: value.description,
        isFree: value.isFree,
        previewThumbnail: value.previewThumbnail,
        isDefault: value.isDefault,
        isSubscriberContent: value.isSubscriberContent,
        priceUsdCents: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.priceUsdCents)),
        priceICP: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.priceICP)),
        images: value.images
    };
}
function from_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    packs: Array<_CatalogItem>;
    modules: Array<_CatalogItem>;
}): {
    packs: Array<CatalogItem>;
    modules: Array<CatalogItem>;
} {
    return {
        packs: from_candid_vec_n22(_uploadFile, _downloadFile, value.packs),
        modules: from_candid_vec_n22(_uploadFile, _downloadFile, value.modules)
    };
}
function from_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    contentType: _ContentType;
    name: string;
    imageCount: bigint;
    description: string;
    isFree: boolean;
    previewThumbnail: string;
    isSubscriberContent: boolean;
    priceUsdCents: [] | [bigint];
}): {
    id: string;
    contentType: ContentType;
    name: string;
    imageCount: bigint;
    description: string;
    isFree: boolean;
    previewThumbnail: string;
    isSubscriberContent: boolean;
    priceUsdCents?: bigint;
} {
    return {
        id: value.id,
        contentType: from_candid_ContentType_n15(_uploadFile, _downloadFile, value.contentType),
        name: value.name,
        imageCount: value.imageCount,
        description: value.description,
        isFree: value.isFree,
        previewThumbnail: value.previewThumbnail,
        isSubscriberContent: value.isSubscriberContent,
        priceUsdCents: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.priceUsdCents))
    };
}
function from_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    defaultIdleAnimationName: [] | [string];
    animations: Array<[string, string]>;
    expressions: Array<[string, string]>;
    defaultExpressionName: [] | [string];
}): {
    defaultIdleAnimationName?: string;
    animations: Array<[string, string]>;
    expressions: Array<[string, string]>;
    defaultExpressionName?: string;
} {
    return {
        defaultIdleAnimationName: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.defaultIdleAnimationName)),
        animations: value.animations,
        expressions: value.expressions,
        defaultExpressionName: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.defaultExpressionName))
    };
}
function from_candid_record_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: boolean;
    expiryDateMs: [] | [bigint];
}): {
    active: boolean;
    expiryDateMs?: bigint;
} {
    return {
        active: value.active,
        expiryDateMs: record_opt_to_undefined(from_candid_opt_n29(_uploadFile, _downloadFile, value.expiryDateMs))
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    learningmodule: null;
} | {
    referencepack: null;
}): ContentType {
    return "learningmodule" in value ? ContentType.learningmodule : "referencepack" in value ? ContentType.referencepack : value;
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ImageSet>): Array<ImageSet> {
    return value.map((x)=>from_candid_ImageSet_n13(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CatalogItem>): Array<CatalogItem> {
    return value.map((x)=>from_candid_CatalogItem_n23(_uploadFile, _downloadFile, x));
}
function to_candid_ContentType_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ContentType): _ContentType {
    return to_candid_variant_n32(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation): __ImmutableObjectStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation | null): [] | [__ImmutableObjectStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_variant_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ContentType): {
    learningmodule: null;
} | {
    referencepack: null;
} {
    return value == ContentType.learningmodule ? {
        learningmodule: null
    } : value == ContentType.referencepack ? {
        referencepack: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
